# -----------------------------------------------------------------------------
# Staging Ortamı İçin Özel Değerler
# -----------------------------------------------------------------------------
# Bu dosya, ana values.yaml dosyasındaki değerleri ezer (override).
# Sadece staging ortamına özel değişiklikleri buraya ekleyin.

# Not: Chart'larınızın bu global değerleri kullanacak şekilde yapılandırıldığından
# emin olmalısınız. Örneğin, deployment.yaml içinde:
# replicas: {{ .Values.global.replicaCount | default .Values.userService.deployment.replicas }}

global:
  environment: "staging"
  # Staging ortamında maliyetleri düşürmek için her servisten 1 kopya çalıştır.
  replicaCount: 1

# Staging ortamı için servislerin daha düşük kaynak limitleri olabilir.
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"