{{- if .Values.global.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecrets.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.imagePullSecrets.dockerconfigjson }}
{{- end }}