apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: {{ .Values.todoService.replicaCount }}
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: todo-service
          image: "{{ .Values.todoService.repository }}:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.todoService.port }}
          env:
            - name: SECRET_KEY
              value: "change-in-production" # Consider using secrets for this
            - name: USER_SERVICE_URL
              value: "http://user-service:{{ .Values.userService.port }}"
