apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.todoService.service.port }}
      targetPort: {{ .Values.todoService.service.targetPort }}
      protocol: TCP
  selector:
    app: todo-service
