apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: {{ .Values.todoService.deployment.replicas }}
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}
      containers:
        - name: todo-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.todoService.image.repository }}:{{ .Values.global.tag | default .Values.todoService.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.todoService.service.targetPort }}
          env:
            - name: SECRET_KEY
              value: {{ .Values.todoService.env.secretKey | quote }}
            - name: USER_SERVICE_URL
              value: {{ .Values.todoService.env.userServiceUrl | quote }}