apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.targetPort }}
      protocol: TCP
  selector:
    app: user-service
