apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.userService.port }}
      targetPort: {{ .Values.userService.port }}
      protocol: TCP
  selector:
    app: user-service
