apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: user-service
          image: "{{ .Values.userService.repository }}:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.userService.port }}
          # Not: env değişkenleri ve problar gibi daha karmaşık yapılandırmaları
          # daha sonra values.yaml'a ekleyerek burayı zenginleştirebilirsiniz.
          env:
            - name: SECRET_KEY
              value: "dummy-secret-key-from-git" # Bu değer Kubernetes Secret'larından gelmelidir.
