apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: {{ .Values.userService.deployment.replicas }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}
      containers:
        - name: user-service
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.userService.image.repository }}:{{ .Values.global.tag | default .Values.userService.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.userService.service.targetPort }}
          # Not: env değişkenleri ve problar gibi daha karmaşık yapılandırmaları
          # daha sonra values.yaml'a ekleyerek burayı zenginleştirebilirsiniz.
          env:
            - name: SECRET_KEY
              value: {{ .Values.userService.env.secretKey | quote }}